queue: VSEng-MicroBuildVS2019

steps:

- checkout: self
  clean: true

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 3.0.100-preview3-010431'
  inputs:
    version: 3.0.100-preview3-010431

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: src\Xamarin.CodeAnalysis.sln
    msbuildArguments: /t:Restore /bl:"$(Build.ArtifactStagingDirectory)\restore.binlog" /m

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: src\Xamarin.CodeAnalysis.sln
    msbuildArguments: /bl:"$(Build.ArtifactStagingDirectory)\build.binlog" /p:TargetVsixContainer=$(Build.ArtifactStagingDirectory)\Xamarin.CodeAnalysis.vsix /m

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: src\*\bin\*\*.Tests.dll
    runInParallel: 'true'
    codeCoverageEnabled: 'true'
    publishRunAttachments: 'true'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: out
    ArtifactType: Container
  condition: always()